version: '3'
services:
    iis-admin:
      build: .
      image: artisticcheese/iis-admin:latest
      environment: 
        - "ContainerAdmin=${ContainerAdmin}"
        - "ContainerPassword=${ContainerPassword}"
        - "SHELL=powershell.exe"
      ports:
        - "80"
        - "55593"
networks:
  default:
    external:
      name: nat