version: '3'
services:
    iis-admin:
      build: .
      image: artisticcheese/iis-admin:latest
      environment: 
        - "SecretLocation=c:\\startup\\creds.json"
        - "SHELL=powershell.exe"
      ports:
        - "80"
        - "55593"
      volumes:
        - d:\docker\logs\:c:\inetpub\logs\logfiles\host
        - d:\docker\freb\:c:\inetpub\logs\logfiles\freb